Vamos a escribir las fórmulas que usaremos para el método de Taylor pero con **coeficientes empezando desde 1 en vez desde cero**. (Esto lo hice por comidad para trabajar con los índices de los arreglos definidos en Julia desde 1 y no desde 0). Dada una función $f(x)$ su desarrollo en Taylor será:

$$ f(x)=\sum_{k=1}^{\infty}f_k (t-t_0)^{k-1}$$


Siguiendo la ecuación diferencial $$ \dot{x}=f(x,t) $$

se tiene una relación de recurrencia para los coeficnietes de la solución $x(t)$ en función de los coeficientes de $f(x,t)$:

$$ x_{k}=\frac{f_{k-1}}{k-1}$$ 

con este cambio de notación, los coeficientes para una función elevada a una potencia $g(x)^a$ estarán dados por:

$$(g^a)_{k}=\frac{1}{g_1}\sum_{i=2}^{k}\left[ \frac{a(i-1)-(k-i)}{k-1} \right] g_i (g^a)_{k+1-i} $$ 

válida $\forall i \geq 2$

para $i=1$ se tiene que $(g^a)_1=g_1^a$

En donde los se ha supuesto que los coficientes de Taylor de la función $g(x)$ existen y además $g_1= g(t_0)\neq 0$

La ecuación diferencial a resolver es

$$ \dot{x}=x^2 \ \mbox{  con la condición inicial  } \ x(t_0=0)=1 $$ 

Antes de atacar la ecuación diferencial, ataquemos el problema de elevar un polinomio $P(x)$ al cuadrado. Aquí a=2 y la ecuación para los coeficientes de trasnforma en 

$$ (p^2)_{k}=\frac{1}{p_1}\sum_{i=2}^{k}\left[ \frac{2(i-1)-(k-i)}{k-1} \right] p_i (p^2)_{k+1-i} $$ 

válida para $k\geq 2$

para $k=1$ se tiene que $(p^2)_1=g_1^2$

In [3]:
#Polinomio de orden M con metaprogramming
m=5
ex="a[1]"
term=0
for i in 2:m+1
    term=string("+a[",i,"]","*t^",i-1)
    ex=ex*term
end
pol=parse(ex)
poli=:(g(t)=$pol)
println(poli)
eval(poli)
#println(ex)
#println(term)

g(t) = a[1] + a[2] * t^1 + a[3] * t^2 + a[4] * t^3 + a[5] * t^4 + a[6] * t^5


g (generic function with 1 method)

In [4]:
a=zeros(m+1) #Defino los coeficientes del polinomio de grado m
for i in 1:m+1
    a[i]=1
end 

In [5]:
a

6-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

$$ (p^2)_{k}=\frac{1}{p_1}\sum_{i=2}^{k}\left[ \frac{2(i-1)-(k-i)}{k-1} \right] p_i (p^2)_{k+1-i} $$ 

válida para $k\geq 2$

para $k=1$ se tiene que $(p^2)_1=g_1^2$

In [6]:
#celda que eleva al cuadrado el polinomio con la formula anterior 
n=2
t0=0
p2=zeros(n*m+1) #coeficientesde p^2
p=zeros(n*m+1) #se necesita este arreglo por que el ciclo for corre desde 1 hasta 2m+1 para 
#calcular los coeficientes de g^2 y el arreglo "a" utilizado para definir al polinomio g es de 
#longitud m+1
[p[i]=a[i] for i=1:m+1] 
p2[1]=p[1]^n
for k in 2:length(p2)
    suma=0
    for i in 2:k
        suma=suma+((2*(i-1)-(k-i))/(k-1))*p[i]*p2[k+1-i]
    end 
    p2[k]=suma/p[1]
end

In [7]:
p2 

11-element Array{Float64,1}:
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
 5.0
 4.0
 3.0
 2.0
 1.0

In [8]:
ex=: "p2[1]"
#ex="a[1]"
term=0
for i in 2:2m+1
    term=string("+",p2[i],"*t^",i-1) #esto es un string
    ex=ex*term
end
ex=parse(ex) #convertimos el string a expresion 
gcuad=: (g2(t)=$ex)
eval(gcuad)

g2 (generic function with 1 method)

In [9]:
gcuad

:(g2(t) = p2[1] + 2.0 * t^1 + 3.0 * t^2 + 4.0 * t^3 + 5.0 * t^4 + 6.0 * t^5 + 5.0 * t^6 + 4.0 * t^7 + 3.0 * t^8 + 2.0 * t^9 + 1.0 * t^10)

Para comprobar que nuestra función de elevar un polinomio al cuadrado está trabajando bien calcularemos:

$$ (1-t)^2=1-2t+t^2$$ y
$$ (3+4t)^2=9+24t+16t^2$$

In [8]:
a=[1,-1] #coeficientes del primer polinomio 
m=1 #grado del polinomio a elevar al cuadrado
n=2
p2=zeros(n*m+1) #coeficientesde p^2
p=zeros(n*m+1) #se necesita este arreglo por que el ciclo for corre desde 1 hasta 2m+1 para 
#calcular los coeficientes de g^2 y el arreglo "a" utilizado para definir al polinomio g es de 
#longitud m+1
[p[i]=a[i] for i=1:m+1] 
p2[1]=p[1]^n
for k in 2:length(p2)
    suma=0
    for i in 2:k
        suma=suma+((2*(i-1)-(k-i))/(k-1))*p[i]*p2[k+1-i]
    end 
    p2[k]=suma/p[1]
end

In [9]:
p2 #coef. del primer binomio, esperamos que sean 1,-2,1

3-element Array{Float64,1}:
  1.0
 -2.0
  1.0

In [10]:
a=[3,4] # coeficientes del segundo binomio
m=1 #grado del polinomio a elevar al cuadrado
n=2
p2=zeros(n*m+1) #coeficientesde p^2
p=zeros(n*m+1) #se necesita este arreglo por que el ciclo for corre desde 1 hasta 2m+1 para 
#calcular los coeficientes de g^2 y el arreglo "a" utilizado para definir al polinomio g es de 
#longitud m+1
[p[i]=a[i] for i=1:m+1] 
p2[1]=p[1]^n
for k in 2:length(p2)
    suma=0
    for i in 2:k
        suma=suma+((2*(i-1)-(k-i))/(k-1))*p[i]*p2[k+1-i]
    end 
    p2[k]=suma/p[1]
end

In [11]:
p2  #coef. del segundo binomio cuadrado, esperamos que sean 9,24,16

3-element Array{Float64,1}:
  9.0
 24.0
 16.0

#Método de taylor para la ecuación diferencial.

$\dot{x}=x^2=f(x,t), $  con    $\ x(t_0=0)=1=x_1$

In [17]:
N=30 #orden de aproximación a la seie de Taylor, ie, cuátons términos tendrá nuestro polinomio
xjet=zeros(2N+1) #arreglos para los jets
fjet=zeros(2N+1)
ϵ=1e-16 #error que ocupamos para definir el paso de integración 
iter=500 #numero de iteraciones 
x=zeros(iter) #Arreglo en donde guardaremos los valores que se van calculando de la función x(t)
t=zeros(iter) #arreglo de tiempos apra la solución
t[1]=0
x[1]=1  #condición inicial
xjet[1]=x[1]
h=0
#----------------------------------
function xaux(t) #esta función construye la serie de Taylor para x(t) a partir del arreglo xjet
    suma=0 #podría intentar sustituir este polinomio usando el metodo de Horner para ser un
    for i in 1:N+1 #poco mas eficiente
        suma=suma+xjet[i]*t^(i-1)
    end 
    return suma
end 
#----------------------------------
for j in 1:1#iter-1 #for que se utiliza para ir "ajustando" la condición inicial con el paso de integracion
xjet[1]=xaux(t[j])
fjet[1]=xjet[1]^2
n=2
p=zeros(2N+1)
#p2=zeros(n*m+1) #coeficientesde p^2 será el arreglo fjet
[p[i]=xjet[i] for i in 1:2N+1] #arreglo auxiliar para calcular los coeficientes 
    for k in 2:N+1
        p[k]=fjet[k-1]/(k-1)
        suma=0
            for i in 2:k
                suma=suma+((2*(i-1)-(k-i))/(k-1))*p[i]*fjet[k+1-i]
            end 
    fjet[k]=suma/p[1]
    end
[xjet[i]=p[i] for i in 1:N+1] 
#--------Necesitamos definir el paso de integración--------
h1=(ϵ/xjet[N])^(1/N)
h2=(ϵ/xjet[N+1])^(1/(N+1))
h=min(h1,h2)
t[j+1]=t[j]+h
x[j+1]=xaux(t[j]+h)    
end


In [22]:
fjet[32]

0.0

In [15]:
xaux(0.12)

1.1363636363636367

In [13]:
exacta(t)=-1/(t-1)

exacta (generic function with 1 method)

In [14]:
exacta(0.12)

1.1363636363636365